### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by domenicoblanco** [gdgpisa/gdgpisa.github.io#1]
All'apertura del sito, Safari su macOS Sierra (penso lo faccia anche Chrome) avvisa che la navigazione non è sicura. Penso che il problema sia il certificato SSL

**Comment by cortinico** [comment]
Si questo andrebbe risolto :(

Penso si debba seguire una cosa del genere:
https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

Il problema e' avere sia il custom domain (gdgpisa.it) che SSL
Stasera provo a dare un'occhiata.

**Comment by cortinico** [comment]
Dovrebbe funzionare adesso, pero' ci vorranno un po' di ore per la modifica dei nameserver. Domani mattina verifico che la cosa sia andata a buon fine :)

**Comment by domenicoblanco** [comment]
Nessun problema, io domani sono libero... Continuo a controllare la propagazione dei DNS e controllo appena sarà completa (dovrebbero iniziare a funzionare sia la webApp che le notifiche push). Chiudo appena sarò certo che il problema è stato risolto. Buona notte!

**Comment by domenicoblanco** [comment]
Il sito è completamente down, hai effettuato il redirect dai nameservers di Cloudflare all'indirizzo di GitHub?

**Comment by cortinico** [comment]
Mi pare che adesso funzioni tutto, non ho toccato nulla ;)

Era un problema di propagazione di DNS. Direi che siamo apposto, chiudiamo?

**Comment by cortinico** [comment]
All fine 🤙
