### ISSUE TITLE
Search bar issue

### ISSUE THREAD

**Issue by giobart** [gdgpisa/gdgpisa.github.io#14]
quando si cerca qualcosa che ha un link esterno ad esempio _"Action on Google"_ viene semplicemente unito il link gdgpisa.it alla url del link venendo così indirizzati ad una pagina che al caso ottimo è inesistente.
Nello specifico caso dell'esempio di cui sopra, si viene indirizzati alla pagina:
_https://gdgpisa.ithttps//www.meetup.com/GDG-Pisa/events/244273880/_

che ovviamente non esiste.

**Comment by cortinico** [comment]
Fixato 🎉
