### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by domenicoblanco** [gdgpisa/gdgpisa.github.io#2]
Sarebbe possibile aggiungere il nostro logo per evitare di linkare i meta tag all'immagine di Facebook? 
![13412226_1557357057906184_386444102369726081_o](https://user-images.githubusercontent.com/9018104/31762659-2ed8358c-b4bc-11e7-89fa-7d2564a125cc.jpg)

**Comment by giulitz189** [comment]
Ti chiedo due cose:
1) L'indirizzo sorgente dell'immagine che vuoi mettere è quello che hai appena postato (da repository Github)?
2) Lo vorresti mettere in sostituzione al logo GDG generico che è presente come header nella pagina?

**Comment by domenicoblanco** [comment]
Ho risolto appena caricando il logo in png dentro /static/img, necessitavo di caricarlo per la WebApp. Non so se voi preferite mettere questo logo a sfavore del logo già presente.

**Comment by cortinico** [comment]
> Non so se voi preferite mettere questo logo a sfavore del logo già presente.

Si sarebbe buono avere il logo con la torre di pisa invece del logo GDG neutro.
Il logo neutro l'avevo messo io come placeholder, ma lo possiamo killare asap

**Comment by domenicoblanco** [comment]
Allora lo modifico subito io stesso

**Comment by domenicoblanco** [comment]
Aspettiamo di avere la versione senza sfondo e poi sostituiamo il file avatar

**Comment by giulitz189** [comment]
Concordo con @cortinico, preferisco il logo del GDG Pisa rispetto a quello generico

**Comment by domenicoblanco** [comment]
Assolutamente favorevole anche io
