### ISSUE TITLE
External link should open on a new tab

### ISSUE THREAD

**Issue by cortinico** [gdgpisa/gdgpisa.github.io#28]
We are missing `target="_blank"` on external links, we should update this to avoid people navigating out from the website.

## Expected Behavior
External link should open on a new tab

## Actual Behavior
External link open on the same tab

## Steps to Reproduce the Problem

  1. E.g. Click on the *Meetup* link on the homepage

## Specifications

  - Browser: Chrome Version 62.0.3202.75 (Official Build) (64-bit)

**Comment by gas3** [comment]
Is this really a bug? Are we sure that we want this behaviour for **all** external links?

**Comment by cortinico** [comment]
At least for the one in the navigation drawer and the one in the "projects" page
