### ISSUE TITLE
Balloons in the About page are too near

### ISSUE THREAD

**Issue by cortinico** [gdgpisa/gdgpisa.github.io#29]
We should increase the spacing of the balloon page on the home page (About), the are really near each other.

## Screenshot
<img width="791" alt="screen shot 2017-11-06 at 9 11 00 am" src="https://user-images.githubusercontent.com/3001957/32431155-9070d9b0-c2d2-11e7-909e-c6c025acd3de.png">

## Specifications

  - Browser: Chrome Version 62.0.3202.75 (Official Build) (64-bit)

**Comment by cortinico** [comment]
So @ar3s3ru this can be closed right?

**Comment by ar3s3ru** [comment]
@cortinico sure!
