### ISSUE TITLE
Cookie policy

### ISSUE THREAD

**Issue by domenicoblanco** [gdgpisa/gdgpisa.github.io#37]
We must create our Cookie Policy and add a bar in the website to accept or refuse our conditions.

http://www.garanteprivacy.it/web/guest/home/docweb/-/docweb-display/docweb/3118884

**Comment by cortinico** [comment]
@domenicoblanco Are we using cookies actually?

**Comment by domenicoblanco** [comment]
I'm quite sure that our push notifications service worker and the PWA use both cookies

**Comment by domenicoblanco** [comment]
Not needed anymore as OneSignal was removed
