### ISSUE TITLE
Bug Header

### ISSUE THREAD

**Issue by domenicoblanco** [gdgpisa/gdgpisa.github.io#7]
Visualizzando il sito in versione mobile, appare il menù ad hamburger ma sotto l'immagine

**Comment by giulitz189** [comment]
Come è che a me non appare proprio?

![](https://user-images.githubusercontent.com/16361287/31780162-37aee3ca-b4f5-11e7-9b95-e75332aabde3.png)

**Comment by domenicoblanco** [comment]
C'è, ma è semi trasparente e si confonde con l'immagine

**Comment by cortinico** [comment]
Eh bisogna cambiare il colore dell'hamburg e farlo bianco quando siamo sulla home

**Comment by cortinico** [comment]
Fixato
