### ISSUE TITLE
Necessità nuovo plugin Jekyll

### ISSUE THREAD

**Issue by domenicoblanco** [gdgpisa/gdgpisa.github.io#9]
Ciao ragazzi, dovremmo integrare un plugin Jekyll per aggiungere il supporto della cache. Dato che il manifest per la webapp richiede per forza che la web app abbia anche un minimo di cache.
Ho trovato un plugin che si chiama Jekyll-offline, lo ho aggiunto al Gemfile ed al _config.yml, qualcuno saprebbe installarlo?

**Comment by cortinico** [comment]
Se lo aggiungi al Gemfile e nel config si installa da "solo" :)
L'unica cosa bisogna verificare che funzioni con github pages.

**Comment by domenicoblanco** [comment]
Stavo guardando il README e mi proponeva di fare un "build Install", non abbiamo quindi bisogno di farlo?

**Comment by cortinico** [comment]
Nono lo fa in automatico il CI di GitHub.
Pero' magari apri una PullRequest per questo commit. Se non sbaglio ti
segnala il fallimento se non riesce ad installare plugin per github pages.

**Comment by domenicoblanco** [comment]
Ok, grazie!!

**Comment by domenicoblanco** [comment]
A quanto pare il plugin non è compatibile con le GitHub pages, secondo voi funzionerebbe la versione cache di Cloudflare?

**Comment by cortinico** [comment]
Qui chiudiamo visto che abbiamo implementato il Service Worker ;)
